version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - syou6162
  ignore:
  - dependency-name: github.com/mackerelio/mackerel-client-go
    versions:
    - 0.14.0
    - 0.15.0
    - 0.16.0
